[package]
name = "nping"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
pnet = "0.35.0"
ctrlc = "3.2"
ratatui = "0.29.0"
tokio = { version = "1.42.0", features = ["full"] }


